# app/routers/__init__.py
from . import users
from . import clinics
from . import services
from . import doctors
from . import appointments
from . import shifts
from . import surgery_bookings
from . import auth
from . import hotels
from . import rooms
from . import activities
from . import bookings
from . import events
from . import ferries
from . import ferry_schedules
from . import ferry_tickets
from . import payments
from . import admin
